export const CONTENT = [
  {
    title: "This is Cats",
    description: "You have caught their attention!",
    images: [
      "/images/cat/cat0.avif",
      "/images/cat/cat1.avif",
      "/images/cat/cat2.avif",
      "/images/cat/cat3.avif",
      "/images/cat/cat4.avif",
      "/images/cat/cat5.avif",
      "/images/cat/cat6.avif",
      "/images/cat/cat7.avif",
      "/images/cat/cat8.avif",
      "/images/cat/cat9.avif",
      "/images/cat/cat10.avif",
    ],
  },
  {
    title: "This is Cats",
    description: "You have caught their attention!",
    images: [
      "/images/cat/cat0.avif",
      "/images/cat/cat1.avif",
      "/images/cat/cat2.avif",
      "/images/cat/cat3.avif",
      "/images/cat/cat4.avif",
      "/images/cat/cat5.avif",
      "/images/cat/cat6.avif",
      "/images/cat/cat7.avif",
      "/images/cat/cat8.avif",
      "/images/cat/cat9.avif",
      "/images/cat/cat10.avif",
    ],
  },
  {
    title: "This is Cats",
    description: "You have caught their attention!",
    images: [
      "/images/cat/cat0.avif",
      "/images/cat/cat1.avif",
      "/images/cat/cat2.avif",
      "/images/cat/cat3.avif",
      "/images/cat/cat4.avif",
      "/images/cat/cat5.avif",
      "/images/cat/cat6.avif",
      "/images/cat/cat7.avif",
      "/images/cat/cat8.avif",
      "/images/cat/cat9.avif",
      "/images/cat/cat10.avif",
    ],
  },
  {
    title: "This is Cats",
    description: "You have caught their attention!",
    images: [
      "/images/cat/cat0.avif",
      "/images/cat/cat1.avif",
      "/images/cat/cat2.avif",
      "/images/cat/cat3.avif",
      "/images/cat/cat4.avif",
      "/images/cat/cat5.avif",
      "/images/cat/cat6.avif",
      "/images/cat/cat7.avif",
      "/images/cat/cat8.avif",
      "/images/cat/cat9.avif",
      "/images/cat/cat10.avif",
    ],
  },
];
